# KNN For iris and wine datasets
***
Rodriguez Nuñez Diego Eduardo


## Iris

Leemos el dataset

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import seaborn as sns
from sklearn.metrics import confusion_matrix
from sklearn import datasets
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [2]:
df = pd.read_csv("Iris.csv")
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm   
0      1            5.1           3.5            1.4           0.2  \
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

Dividimos el dataset en 70% para entrenar y 30% para probar

In [3]:
x = df.drop("Species", axis=1)
y = df["Species"]

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3)

df_train = pd.concat([x_train,y_train],axis=1)
df_test = pd.concat([x_test,y_test],axis=1)

Calculamos las distancias euclidianas

In [8]:
def dist_euclidiana(p1,p2):
    return np.sqrt(np.sum(p1-p2)**2)

### KNN

In [1]:
def knn(train_x,train_y,point,k):
    distance=[]
    for i in range(len(train_x)):
        dist=dist_euclidiana(train_x[i],point)
        distance.append(dist)
    distances=np.array(distance)
    near_neighbors = np.argsort(distances)[:k]
    near_clases = train_y[near_neighbors]
    unique_clases, count_clases = np.unique(near_clases,return_counts=True)
    
    return unique_clases[np.argmax(count_clases)]

#### Test

In [10]:
k_values = [1,3,5]

predictions_dict = {}

for k in k_values:
    predictions = []
    for i in range(len(x_test)):
        test_point = x_test.iloc[i].values
        prediction = knn(x_train.values,y_train.values,test_point,k)
        predictions.append(prediction)

    predictions_dict[k] = predictions

for k in k_values:
    print(f"Predictions for k={k}")
    for i in range(len(x_test)):
        print(f"Prediction for the point {i+1}: Prediction = {predictions[i]}")

Predictions for k=1
Prediction for the point 1: Prediction = Iris-virginica
Prediction for the point 2: Prediction = Iris-setosa
Prediction for the point 3: Prediction = Iris-versicolor
Prediction for the point 4: Prediction = Iris-versicolor
Prediction for the point 5: Prediction = Iris-setosa
Prediction for the point 6: Prediction = Iris-versicolor
Prediction for the point 7: Prediction = Iris-virginica
Prediction for the point 8: Prediction = Iris-virginica
Prediction for the point 9: Prediction = Iris-setosa
Prediction for the point 10: Prediction = Iris-setosa
Prediction for the point 11: Prediction = Iris-versicolor
Prediction for the point 12: Prediction = Iris-virginica
Prediction for the point 13: Prediction = Iris-setosa
Prediction for the point 14: Prediction = Iris-setosa
Prediction for the point 15: Prediction = Iris-virginica
Prediction for the point 16: Prediction = Iris-versicolor
Prediction for the point 17: Prediction = Iris-versicolor
Prediction for the point 18: Pre

### Matriz de confusion

In [18]:
confusion = confusion_matrix(y_test,predictions)
print("Confusion Matrix")
print(confusion)

Confusion Matrix
[[14  0  0]
 [ 0 18  1]
 [ 0  0 12]]


#### Calculamos metricas

In [12]:
accuracy = accuracy_score(y_test, predictions)

print(f"Precisión: {accuracy}")

Precisión: 0.9777777777777777


## Wine

In [23]:
wine = datasets.load_wine()
data = wine.data
df2 = pd.DataFrame(data,columns=wine.feature_names)
df2['target']= wine.target
df2

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols   
0      14.23        1.71  2.43               15.6      127.0           2.80  \
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue   
0          3.06                  0.28             2.29             5.64  1.04  \
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     od280/od315_of_diluted_wines  proline  target  
0                            3.92   1065.0       0  
1                            3.40   1050.0       0  
2                            3.17   1185.0       0  
3                            3.45   1480.0       0  
4                            2.93    735.0       0  
..                            ...      ...     ...  
173                          1.74    740.0       2  
174                          1.56    750.0       2  
175                          1.56    835.0       2  
176                          1.62    840.0       2  
177                          1.60    560.0       2  

[178 rows x 14 columns]

In [24]:
x = df2.drop("target",axis=1)
y = df2["target"]

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3)

df_train = pd.concat([x_train,y_train],axis=1)
df_test = pd.concat([x_test,y_test],axis=1)

In [25]:
k_values = [1,3,5]

predictions_dict = {}

for k in k_values:
    predictions = []
    for i in range(len(x_test)):
        test_point = x_test.iloc[i].values
        prediction = knn(x_train.values,y_train.values,test_point,k)
        predictions.append(prediction)

    predictions_dict[k] = predictions

for k in k_values:
    print(f"Predictions for k={k}")
    for i in range(len(x_test)):
        print(f"Prediction for the point {i+1}: Prediction = {predictions[i]}")

Predictions for k=1
Prediction for the point 1: Prediction = 0
Prediction for the point 2: Prediction = 1
Prediction for the point 3: Prediction = 2
Prediction for the point 4: Prediction = 0
Prediction for the point 5: Prediction = 1
Prediction for the point 6: Prediction = 1
Prediction for the point 7: Prediction = 1
Prediction for the point 8: Prediction = 1
Prediction for the point 9: Prediction = 0
Prediction for the point 10: Prediction = 2
Prediction for the point 11: Prediction = 1
Prediction for the point 12: Prediction = 0
Prediction for the point 13: Prediction = 1
Prediction for the point 14: Prediction = 0
Prediction for the point 15: Prediction = 1
Prediction for the point 16: Prediction = 1
Prediction for the point 17: Prediction = 1
Prediction for the point 18: Prediction = 1
Prediction for the point 19: Prediction = 0
Prediction for the point 20: Prediction = 2
Prediction for the point 21: Prediction = 2
Prediction for the point 22: Prediction = 1
Prediction for the po

In [26]:
confusion = confusion_matrix(y_test,predictions)
print("Confusion Matrix")
print(confusion)

Confusion Matrix
[[15  1  2]
 [ 0 17  2]
 [ 0 11  6]]


In [27]:
accuracy = accuracy_score(y_test, predictions)

print(f"Precisión: {accuracy}")

Precisión: 0.7037037037037037
